services:
  jupyter:
    container_name: gpu-jl

    build:
      context: ${HOME}/scripts
      dockerfile: Dockerfile
    image: alfrizz/gpu-jl:latest

    restart: unless-stopped

    gpus: all
    cpus: "14.0"         # Leaves 2 cores for WSL background tasks
    mem_limit: "42g"     # Gives WSL a 6GB buffer to breathe
    shm_size: 8g         # Lowered since we are using 0 workers for now
    ports:
      - "8888:8888"

    volumes:        
      - "/home/alfrizz/docker_tmp:/tmp"
      - "/home/alfrizz:/workspace"  # Local Linux storage

    working_dir: /workspace

    entrypoint: ["/usr/local/bin/entrypoint.sh"]

    environment:
      - MAX_WAIT=30
      - ALPACA_KEY_live=${ALPACA_KEY_live}
      - ALPACA_SECRET_live=${ALPACA_SECRET_live}

    command:
      - jupyter
      - lab
      - --no-browser
      - --ip=0.0.0.0
      - --allow-root
      - --NotebookApp.token=
      - --ServerApp.root_dir=/workspace


